### PR TITLE
TF-M v2.0.0 upmerge

### PR DESCRIPTION
**Pull request by mswarowsky**
Merging TF-Mv2.0.0 tag

### CODE REVIEW

**Comment by d3zd3z** [comment]
The new TF-M 2.0 pulls in the lpc SDK at version 2.13.1 instead of the 2.10 that is cherry-picked into this version. I can come up with a new PR with this in the next day or so.

**Comment by mswarowsky** [comment]
> The new TF-M 2.0 pulls in the lpc SDK at version 2.13.1 instead of the 2.10 that is cherry-picked into this version. I can come up with a new PR with this in the next day or so.

Ok then I remove the cherry-picked commit here

**Comment by mswarowsky** [comment]
@d3zd3z Is there any update on the SDK update? Did overlook the PR?

**Comment by d3zd3z** [comment]
The LPC SDK looks ok. I had suggested we not support this target, but it looks like this should work. I still hope NXP can better organize this so we don't have multiple copies of the SDK in the tree.

**Review by d3zd3z — APPROVED** [review]

**Comment by carlescufi** [comment]
@SebastianBoe can you please take a look?

**Comment by SebastianBoe** [comment]
will do

**Comment by SebastianBoe** [comment]
@mswarowsky : FYI needs rebase.

"This branch cannot be rebased due to conflicts"

**Comment by SebastianBoe** [comment]
In https://github.com/mswarowsky/trusted-firmware-m/commit/eb0d2232c7b9bea0a47a11fa51ac49117e20400f we say that we this patch is temporary until 8602 is resolved.

But 8602 is resolved.

Can we cherry-pick the fix from 8602 instead of using our own workaround?

**Review by SebastianBoe — APPROVED** [review]

**Comment by mswarowsky** [comment]
> @mswarowsky : FYI needs rebase.
> 
> "This branch cannot be rebased due to conflicts"

That is some issue with Github in the upmerge, the the merge for this PR has to done from command line, where is should be conflict free. 


> In [mswarowsky@eb0d223](https://github.com/mswarowsky/trusted-firmware-m/commit/eb0d2232c7b9bea0a47a11fa51ac49117e20400f) we say that we this patch is temporary until 8602 is resolved.
> 
> But 8602 is resolved.
> 
> Can we cherry-pick the fix from 8602 instead of using our own workaround?

It is in this commit: https://github.com/Mbed-TLS/mbedtls/commit/8f1c36df00f6cdca0ba0bb04a497057c37248017 but due this being a merge commit, it was not cherry-pickable for me in mbed TLS. 
Added a comment in the commit message so in easier to see that it is not needed anymore when the next upmerge is done.

**Pull request merged**
