### PR TITLE
tfm: platform: lpc55s69 support

### PR DESCRIPTION
**Pull request by agansari**
Adds definitions to help run MCUboot with TFM on LPC55S69.

LPC55S69 is memory constrained to run both TFM and MCUBoot with upgrades.
tfm_ns image is rather large, this means that we need differential partitioning of the onboard flash memory, see BUILD_S_ONLY.
tfm_s build as small size release, see Minsizerel.

Depends on upstream TFM: https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/5534 (manually patched here)

Todo:
 - ~~Move  CMAKE_BUILD_TYPE=Minsizerel BUILD_S_ONLY=True to Zephyr build control~~
 - ~~change mcuboot upgrade from overwrite type to swap move~~
 - ~~update size comments~~

### CODE REVIEW

**Comment by agansari** [comment]
Can't add review, tagging you guys here:
@microbuilder @d3zd3z @MaureenHelm @galak

**Comment by agansari** [comment]
Enabled SWAP_MOVE in latest commit

**Comment by agansari** [comment]
Pass CMAKE_BUILD_TYPE=Minsizerel BUILD_S_ONLY=True as EXTRA_ARGS

**Review by d3zd3z — APPROVED** [review]

**Comment by agansari** [comment]
@microbuilder can we have a review on this PR or should I wait for the updated TFM release on zephyrproject?
Also I think https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/5534 should be merged in upstream TFM before.

**Comment by galak** [comment]
> @microbuilder can we have a review on this PR or should I wait for the updated TFM release on zephyrproject?
> Also I think https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/5534 should be merged in upstream TFM before.

FYI: @microbuilder is on vacation this week.

**Comment by ioannisg** [comment]
@agansari (CC @galak @microbuilder ) I think this patch needs to come from the upstream project via an up-merge. Once the Tf-M patch is merged, we can initiate an upmerge here.

**Comment by agansari** [comment]
Closing this PR as it's incompatible with upcoming PR #15
Will resume these changes after #15 is merged.

**Pull request closed without merging**
