### PR TITLE
TF-M: nordic_nrf: update to use nrfx IRQ numbers instead of nRF MDK IRQn

### PR DESCRIPTION
**Pull request by joerchan**

### CODE REVIEW

**Review by awojasinski-nordicsemi — APPROVED** [review]
Looks good to me 😃

**Review by anangl — APPROVED** [review]

**Comment by joerchan** [comment]
DNM: Submitting to upstream first.

**Comment by joerchan** [comment]
@microbuilder No, I am submitting them upstream, but I don't think we need to wait for them to be actually merged in order to continue with this PR. Since Sebastian has already approved them in upstream PR I don't expect that these will be changed.

https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/17473
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/17474

**Comment by microbuilder** [comment]
@joerchan Please comment back here if these don't, for whatever unexpected reason, get merged in upstream then. Thanks.

**Review by microbuilder — APPROVED** [review]

**Pull request merged**
