### PR TITLE
TFM: Update to v1.3.0-rc1

### PR DESCRIPTION
**Pull request by oyvindronningstad**

### CODE REVIEW

**Review by galak — APPROVED** [review]
Probably good to sync to TF-Mv1.3.0-RC1 now that its out.

**Comment by oyvindronningstad** [comment]
> 
> 
> Probably good to sync to TF-Mv1.3.0-RC1 now that its out.

Done

**Review by galak — COMMENTED** [review]
Some how we seem to be missing:
```
 config/build_type/debug.cmake                                     |   10 ----------
 config/build_type/minsizerel.cmake                                |   10 ----------
 config/build_type/release.cmake                                   |   11 -----------
```

**Comment by oyvindronningstad** [comment]
> 
> 
> Some how we seem to be missing:
> 
> ```
>  config/build_type/debug.cmake                                     |   10 ----------
>  config/build_type/minsizerel.cmake                                |   10 ----------
>  config/build_type/release.cmake                                   |   11 -----------
> ```

@galak Thanks, they were ignored by tfm's .gitignore.

**Review by microbuilder — APPROVED** [review]

**Review by ioannisg — CHANGES_REQUESTED** [review]
I think this needs a README update. Let me know if i missed that

**Comment by ioannisg** [comment]
I have a feeling that we do not need, any more, the fixes for the STM scripts, since, at least, the TFM_UPdate.sh is not used any more, by default. It is not a problem to keep the patches, though, since the scripts still exist.  Just a not for future cleanup.

**Review by ioannisg — APPROVED** [review]

**Comment by galak** [comment]
> I have a feeling that we do not need, any more, the fixes for the STM scripts, since, at least, the TFM_UPdate.sh is not used any more, by default. It is not a problem to keep the patches, though, since the scripts still exist. Just a not for future cleanup.

I wondered about upstreaming some of those changes.  But good to know that they might not be needed.

**Comment by oyvindronningstad** [comment]
> 
> 
> > I have a feeling that we do not need, any more, the fixes for the STM scripts, since, at least, the TFM_UPdate.sh is not used any more, by default. It is not a problem to keep the patches, though, since the scripts still exist. Just a not for future cleanup.
> 
> I wondered about upstreaming some of those changes. But good to know that they might not be needed.

They actually were needed. I tried first without, but the CI failed.

**Pull request merged**
