### PR TITLE
Remove mbed-crypto

### PR DESCRIPTION
**Pull request by galak**
tfm pulls its own copy of mbed-crypto now so remove our local copy

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Review by ioannisg — APPROVED** [review]
I am OK with this. It was on my todo list. Thanks
Any concerns @oyvindronningstad?

**Review by microbuilder — APPROVED** [review]

**Review by oyvindronningstad — APPROVED** [review]

**Comment by d3zd3z** [comment]
Probably not best to point out here, but just as a heads up, the upstream mbed-crypto repo is deprecated. The functionality is being maintained within the mbedtls repo.

**Comment by ioannisg** [comment]
> Probably not best to point out here, but just as a heads up, the upstream mbed-crypto repo is deprecated. The functionality is being maintained within the mbedtls repo.

@d3zd3z yeap that was communicated but no harm by an extra notification about it :)

**Comment by ioannisg** [comment]
@galak I force-pushed to reword the commit title only.

**Pull request merged**
